apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
  - name: mongo
    image: mongo:4.2.20
    command:
    - /bin/bash
    - -c
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "carlos"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "aS45DffW32$eerf$4514SSAds"
    ports:
    - containerPort: 27017